import test from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'
import { buildScenarios } from '../demo/fixture'

test('fixture scenarios exercise coverage and can be regenerated byte-for-byte', () => {
  const scenarios = buildScenarios()
  assert.equal(scenarios[0].result.observed, 93)
  assert.equal(scenarios[1].result.observed, 91)
  assert.equal(scenarios[2].result.asOf, '2026-08-25')
  assert.equal(scenarios[3].result.observed, 0)
  execFileSync(process.execPath, ['--import', 'tsx', 'scripts/build-demo.ts'])
  const first = readFileSync('demo-dist/index.html')
  execFileSync(process.execPath, ['--import', 'tsx', 'scripts/build-demo.ts'])
  assert.deepEqual(readFileSync('demo-dist/index.html'), first)
  assert.ok(!first.toString().includes('/*__DEMO_DATA__*/'))
})
